AdminPanel.UI/Controllers/ProductController.cs
using AdminPanel.Business.Service;
using AdminPanel.Data.Model;
using AdminPanel.Data.Model.ViewModel;
using AdminPanel.UI.ActionFilter;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminPanel.UI.Controllers
{
    [Auth]
    public class AsyncProductController : AsyncController
    {
        private readonly IProductService ProductService;

        public AsyncProductController()
        {
            ProductService = new ProductService();
        }


        [HttpPost]
        public JsonResult UpsertProduct(ProductVM model)
        {
            if (model.ProductModel.Id == 0)
                ModelState.Remove("ProductModel.Id");

            if (!ModelState.IsValid)
            {
                return new JsonResult
                {
                    Data = new ResultVM
                    {
                        ErrorMessage = MvcHelper.ResolveModelState(ModelState.Values.ToList()),
                        IsSuccess = false
                    }
                };
            }

            model.ProductModel.CategoryId = model.SelectedProductCategoryId;

            var addResult = this.ProductService.Add(model.ProductModel);

            return new JsonResult
            {
                Data = new ResultVM
                {
                    IsSuccess = addResult.IsSuccess,
                    ErrorMessage = addResult.Errors
                }
            };
        }

    }
    
    [Auth]
    public class ProductController : Controller
    {
        private readonly IProductService ProductService;
        private readonly IProductCategoryService ProductCategoryService;

        public ProductController()
        {
            ProductService = new ProductService();
            ProductCategoryService = new ProductCategoryService();
        }


        [HttpGet]
        public JsonResult GetProductById(long Id)
        {
            ProductVM productVM = new ProductVM();
            productVM.ProductModel = this.ProductService.GetById(Id);

            return Json(productVM, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult GetProductList()
        {
            var result = this.ProductService.GetAll();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult DeleteProduct(long Id)
        {
            var result = this.ProductService.Delete(Id);

            return new JsonResult
            {
                Data = new ResultVM
                {
                    IsSuccess = result,
                    ErrorMessage = result == false ? new List<string> { $"{Id} nolu ürün silinemedi" } : new List<string> { }
                }
            };
        }

        [HttpGet]
        public ActionResult List()
        {

            ProductVM productVM = new ProductVM();
            productVM.ProductCategoryList = this.ProductCategoryService.GetAll();

            return View(productVM);
        }
    }
}

AdminPanel.UI/Views/Product/List.cshtml
@model  AdminPanel.Data.Model.ViewModel.ProductVM

@{ ViewBag.Title = "Ürün Liste";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Ürün Listesi
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Ürün</a></li>
            <li class="active">Liste</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <!-- /.box -->
                <div class="box">
                    <div class="box-header">
                        @*<h3 class="box-title"></h3>*@
                    </div>
                    <div class="box-header">
                        <button type="button" onclick="AddOrEditModal()" class="btn btn-primary">Yeni Ekle</button>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">

                        <table id="productList" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Ürün İsmi</th>
                                    <th>Birim</th>
                                    <th>Fiyat</th>
                                    <th>Max Sepet Adet</th>
                                    <th>Kategori</th>
                                    <th>Aktif</th>
                                    <th>İşlemler</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<!-- Modal -->

<div class="modal fade" id="modal-UpsertProduct">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Yeni Ürün Ekle</h4>
                <h4 class="modal-title" id="modal-UpsertProduct_HeaderInfo"></h4>
            </div>

            @using (Html.BeginForm("UpsertProduct", "AsyncProduct", FormMethod.Post, new { id = "FormUpsertProduct", app = @Model }))
            {
<div class="modal-body">
    @Html.HiddenFor(m => m.ProductModel.Id)
    <div class="row form-group">
        <div class="col-md-12">
            @Html.LabelFor(m => m.ProductModel.Name, new { @class = "col-form-label" })
            @Html.TextBoxFor(m => m.ProductModel.Name, new { @type = "text", @class = "form-control" })
        </div>
    </div>
    <div class="row form-group">

        <div class="col-md-6">
            @Html.LabelFor(m => m.ProductModel.PriceText, new { @class = "col-form-label" })
            @Html.TextBoxFor(m => m.ProductModel.PriceText, "{0:F2}", new { @type = "number", max="99999", @min = "0.00", @step = "0.05", @Value = "1.00", @class = "form-control" })
        </div>
        <div class="col-md-6">
            @Html.LabelFor(m => m.ProductModel.MaxCartAmount, new { @class = "col-form-label" })
            @Html.TextBoxFor(m => m.ProductModel.MaxCartAmount, new { @type = "number", @min = "1", @step = "1", @Value = "1", @class = "form-control" })
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-6">
            @Html.LabelFor(m => m.ProductCategoryList, new { @class = "col-form-label" })
            @Html.DropDownListFor(model => model.SelectedProductCategoryId,
                              new SelectList(Model.ProductCategoryList, "Id", "Name"), "- Lütfen Kategori Seçin -", new { @class = "select2", })
        </div>
        <div class="col-md-6">
            @Html.LabelFor(m => m.ProductModel.MeasurementTypeEnum, new { @class = "col-form-label select2" })
            @Html.EnumDropDownListFor(
                                                                             x => x.ProductModel.MeasurementTypeEnum,
                                                                             "Birim Seçiniz",
                                                                             new { @class = "form-control" })

        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-6">
            @Html.LabelFor(m => m.ProductModel.StatusFCheckBox, new { @class = "col-form-label" })
            @Html.CheckBoxFor(m => m.ProductModel.StatusFCheckBox)
        </div>
    </div>
</div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Kapat</button>
                    <button type="submit" class="btn btn-primary">Kaydet</button>
                </div>}
        </div>

    </div>
    <!-- /.modal-content -->
</div>
<!-- /.modal-dialog -->

<script type="text/javascript">

    (function () {

        $('#FormUpsertProduct').ajaxForm({
            beforeSend: function () {
                //$.blockUI({ message: $('#domMessage') });
            },
            success: function (data) {
                debugger;
                if (!data.IsSuccess) {
                    Notify('Ürün Eklenemedi', data.ErrorMessage.toString(), 'warning');
                }
                else {

                    Notify('Başarılı', "Ürün Eklendi", 'succuess');
                    $('#modal-UpsertProduct').modal("toggle");
                }

            }, complete: function (xhr) {
                ProductListTableReload();
            }

        })

    })();


    function AddOrEditModal(Id) {
        debugger;
        $("#ProductModel_Id").val('');
        $("#modal-UpsertProduct").find('h4')[0].innerHTML = "Yeni Ürün Ekle";
        $('#SelectedProductCategoryId').val('');
        $('#SelectedProductCategoryId').trigger('change');
        $('#ProductModel_MeasurementTypeEnum').val('0');
        $('#ProductModel_MeasurementTypeEnum').trigger('change');
        $("#ProductModel_Name").val('');
        $("#ProductModel_MaxCartAmount").val('1');
        $("#ProductModel_PriceText").val('1');

        if (Id != null) {

            //$.blockUI({ message: $('#domMessage') });
            $.ajax({
                url: "/Product/GetProductById?Id=" + Id,
                type: 'GET',

                datatype: 'json',
                success: function (data) {
                    debugger;
                    $("#ProductModel_Id").val(data.ProductModel.Id);
                    $("#ProductModel_Name").val(data.ProductModel.Name);
                    $("#ProductModel_MaxCartAmount").val(data.ProductModel.MaxCartAmount);
                    $("#ProductModel_PriceText").val(data.ProductModel.Price);

                    if (data.ProductModel.Status == 0)
                        $('#ProductModel_StatusFCheckBox').prop('checked', true);
                    else
                        $('#ProductModel_StatusFCheckBox').prop('checked', false);

                    $('#SelectedProductCategoryId').val(data.ProductModel.CategoryId);
                    $('#SelectedProductCategoryId').trigger('change');


                    $('#ProductModel_MeasurementTypeEnum').val(data.ProductModel.MeasurementType);
                    $('#ProductModel_MeasurementTypeEnum').trigger('change');


                    $("#modal-UpsertProduct").find('h4')[0].innerHTML = "(" + data.ProductModel.Id + ") nolu Ürünü Güncelle";

                    //$("#SelectedProductCategoryId").val(data.ProductModel.CategoryId).trigger("chosen:updated");
                    //$("#Branch_Amount").val(data.Branch.Amount);
                    //$("#Branch_ValidTo").val(data.Branch.ValidTo);
                    //$("#Branch_ValidFrom").val(data.Branch.ValidFrom);
                    //$("#frmDrBranchProviderSubType_Modal").find('h4')[0].innerHTML = data.Branch.ModalPopupDesc;
                    //$.unblockUI();
                }

            });
        }

        $('#modal-UpsertProduct').modal("toggle");
    }

    function ProductListTableReload() {
        debugger;
        $.ajax({
            type: "GET",
            url: "/Product/GetProductList",
            contentType: "application/json; charset=utf-8",
            dataType: "json", data: "{}",
            success: OnSuccess,
            failure: function (response) {

            },
            error: function (response) {

            }
        });

        function OnSuccess(response) {
            debugger;
            $('#productList').DataTable().destroy();

            $('#productList').DataTable({
                'paging': true,
                //'lengthMenu': [[10, 25, 50, -1], [10, 25, 50, "All"]],
                'lengthChange': true,
                'searching': true,
                'ordering': true,
                'info': true,
                data: response,
                columns: [
                    {'data':'Id'},
                    { 'data': 'Name' },
                { 'data': 'MeasurementTypeText' },
                { 'data': 'Price' },
                { 'data': 'MaxCartAmount' },
                { 'data': 'Category.Name' },
                { 'data': "StatusFCheckBox" },
                {
                    "data": null,
                    "render": function (data) {

                        return '<button type="button" onclick="AddOrEditModal(' + data.Id + ')" class="btn btn-success"><i class="fa fa-pencil-square-o"></i></button>' +
                            '<button type="button" onclick="ConfirmViaFunc(\'Sil\',\'Silmek istediğinizden emin misiniz ?\',\'warning\',\'DeleteProduct\',' + data.Id + ') " class="btn btn-danger"><i class="fa fa-trash-o"></i></button>';
                    }
                }
                ],
                'autoWidth': false
            });
        }
    }

    function DeleteProduct(id) {
        if (id != null) {
            $.ajax({
                url: "/Product/DeleteProduct",
                type: 'POST',
                data: { 'Id': id },
                datatype: 'json',
                success: function (data) {
                    if (data.IsSuccess == true) {
                        Notify('Başarılı', 'Ürün Silinmistir', 'success');
                        ProductListTableReload();
                    }
                    else
                        Notify('Başarısız', data.ErrorMessage.toString(), 'warning');
                }
            });
        }
    }

    $(document).ready(function () {
        $("#SelectedProductCategoryId").select2();
        ProductListTableReload();
    });

</script>

}