AdminPanel.UI/Controllers/CategoryController.cs
using AdminPanel.Business.Service;
using AdminPanel.Data.Model.ViewModel;
using AdminPanel.UI.ActionFilter;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminPanel.UI.Controllers
{
    [Auth]
    public class AsyncCategoryController : AsyncController
    {
        private readonly IProductCategoryService ProductCategoryService;

        public AsyncCategoryController()
        {
            ProductCategoryService = new ProductCategoryService();
        }


        [HttpPost]
        public JsonResult UpsertCategory(CategoryVM model)
        {
            if (model.ProductCategoryModel.Id == 0)
                ModelState.Remove("ProductCategoryModel.Id");

            ModelState.Remove("SelectedParentProductCategoryId");

            if (!ModelState.IsValid)
            {
                return new JsonResult
                {
                    Data = new ResultVM
                    {
                        ErrorMessage = MvcHelper.ResolveModelState(ModelState.Values.ToList()),
                        IsSuccess = false
                    }
                };
            }

            model.ProductCategoryModel.ParentId = model.SelectedParentProductCategoryId > 0 ? model.SelectedParentProductCategoryId : (long?)null;
            var addResult = this.ProductCategoryService.Add(model.ProductCategoryModel);

            return new JsonResult
            {
                Data = new ResultVM
                {
                    IsSuccess = addResult.IsSuccess,
                    ErrorMessage = addResult.Errors
                }
            };
        }


    }
   
    [Auth]
    public class CategoryController : Controller
    {
        private readonly IProductCategoryService ProductCategoryService;

        public CategoryController()
        {
            ProductCategoryService = new ProductCategoryService();
        }

        // GET: Category
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetCategoryList()
        {
            var result = this.ProductCategoryService.GetAll();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult List()
        {

            CategoryVM categoryVM = new CategoryVM();
            categoryVM.ProductCategoryList = this.ProductCategoryService.GetAll();

            return View(categoryVM);
        }

        [HttpGet]
        public JsonResult GetCategoryById(long Id)
        {
            CategoryVM categoryVM = new CategoryVM();
            categoryVM.ProductCategoryModel = this.ProductCategoryService.GetById(Id);

            return Json(categoryVM, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult UpsertCategory(CategoryVM model)
        {
            if (model.ProductCategoryModel.Id == 0)
                ModelState.Remove("ProductCategoryModel.Id");

            if (!ModelState.IsValid)
            {
                return new JsonResult
                {
                    Data = new ResultVM
                    {
                        ErrorMessage = MvcHelper.ResolveModelState(ModelState.Values.ToList()),
                        IsSuccess = false
                    }
                };
            }

            model.ProductCategoryModel.ParentId = model.SelectedParentProductCategoryId > 0 ? model.SelectedParentProductCategoryId : (long?)null;
            var addResult = this.ProductCategoryService.Add(model.ProductCategoryModel);

            return new JsonResult
            {
                Data = new ResultVM
                {
                    IsSuccess = addResult.IsSuccess,
                    ErrorMessage = addResult.Errors
                }
            };
        }


        [HttpPost]
        public JsonResult DeleteCategory(long Id)
        {
            var result = this.ProductCategoryService.Delete(Id);

            return new JsonResult
            {
                Data = new ResultVM
                {
                    IsSuccess = result,
                    ErrorMessage = result == false ? new List<string> { $"{Id} nolu category silinemedi" } : new List<string> { }
                }
            };
        }

    }
}

AdminPanel.UI/Views/Category/List.cshtml
@model  AdminPanel.Data.Model.ViewModel.CategoryVM


@{ ViewBag.Title = "Kategori Liste";
    Layout = "~/Views/Shared/_Layout.cshtml"; }



<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Category Listesi
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Kategori</a></li>
            <li class="active">Liste</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <!-- /.box -->
                <div class="box">
                    <div class="box-header">
                        @*<h3 class="box-title"></h3>*@
                    </div>
                    <div class="box-header">
                        <button type="button" onclick="AddOrEditModal()" class="btn btn-primary">Yeni Ekle</button>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">

                        <table id="categoryList" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Görsel</th>
                                    <th>Kategori İsmi</th>
                                    <th>Bağlı Olduğu</th>
                                    <th>Aktif</th>
                                    <th>İşlemler</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<!-- Modal -->


<div class="modal fade" id="modal-UpsertCategory">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Yeni Category Ekle</h4>
                <h4 class="modal-title" id="modal-UpsertProduct_HeaderInfo"></h4>
            </div>

            @using (Html.BeginForm("UpsertCategory", "AsyncCategory", FormMethod.Post, new { id = "FormUpsertCategory" }))
            {
<div class="modal-body">
    @Html.HiddenFor(m => m.ProductCategoryModel.Id)
    <div class="row form-group">
        <div class="col-md-12">
            @Html.LabelFor(m => m.ProductCategoryModel.Name, new { @class = "col-form-label" })
            @Html.TextBoxFor(m => m.ProductCategoryModel.Name, new { @type = "text", @class = "form-control" })
        </div>
    </div>

    <div class="row form-group">
        <div class="col-md-6">
            @Html.LabelFor(m => m.ProductCategoryList, new { @class = "col-form-label" })
            @Html.DropDownListFor(model => model.SelectedParentProductCategoryId,
                                                                                                     new SelectList(Model.ProductCategoryList, "Id", "Name"), "- Lütfen Kategori Seçin -", new { @class = "select2", })
        </div>
        <div class="col-md-6">
            <input type='file' class="custom-file-input" id="ProductCategoryModel.Media.HttpPostedFileBase" name="ProductCategoryModel.Media.HttpPostedFileBase" /> <label class="custom-file-label" for="customFile">Choose file</label>
            <img id="fupPreview" width="100" height="100" src="#" alt="" />
        </div>
        @*<input type="file" class="custom-file-input" id="customFile">
            <label class="custom-file-label" for="customFile">Choose file</label>*@
    </div>
    <div class="row form-group">
        <div class="col-md-6">
            @Html.LabelFor(m => m.ProductCategoryModel.StatusFCheckBox, new { @class = "col-form-label" })
            @Html.CheckBoxFor(m => m.ProductCategoryModel.StatusFCheckBox)
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Kapat</button>
        <button type="submit" class="btn btn-primary">Kaydet</button>
    </div>
</div>}
        </div>
        <!-- /.modal-content -->
    </div>
</div>


<script type="text/javascript">

function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#fupPreview').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}

$(".custom-file-input").change(function () {
    debugger;
    readURL(this);
});


function CategoryListTableReload() {
    debugger;

    $.ajax({
        type: "GET",
        url: "/Category/GetCategoryList",
        contentType: "application/json; charset=utf-8",
        dataType: "json", data: "{}",
        success: OnSuccess,
        failure: function (response) {

        },
        error: function (response) {

        }
    });

    function OnSuccess(response) {
        debugger;
        $('#categoryList').DataTable().destroy();

        $('#categoryList').DataTable({
            'paging': true,
            //'lengthMenu': [[10, 25, 50, -1], [10, 25, 50, "All"]],
            'lengthChange': true,
            'searching': true,
            'ordering': true,
            'info': true,
            data: response,
            columns: [
                { 'data': 'Id' },
                {
                    "data": null,
                    "render": function (data) {
                        if (data.Media != null && data.Media.Link != null) {
                            return '<img id="img" width="100" height="100" src="' + window.location.protocol + '//' + window.location.host + '/' + data.Media.Link + '" alt="">';
                        }
                        else {
                            return '<img id="img" width="100" height="100" src="' + window.location.protocol + '//' + window.location.host + '/Uploads/Media/noimage.png" alt="">';
                        }
                    }
                },
                { 'data': 'Name' },
                {
                    "data": null,
                    "render": function (data) {
                        if (data.ParentId != null && data.ParentId > 0 && data.ParentProductCategory != null) {
                            ParentCategoryName = "";
                            debugger;
                            recursiveIteration(data);

                            return '<span><b>' + ParentCategoryName+ '</b></span>';
                        }
                        return '';
                    }
                },
                { 'data': "StatusFCheckBox" },
                {
                    "data": null,
                    "render": function (data) {

                        return '<button type="button" onclick="AddOrEditModal(' + data.Id + ')" class="btn btn-success"><i class="fa fa-pencil-square-o"></i></button>' +
                            '<button type="button" onclick="ConfirmViaFunc(\'Sil\',\'Silmek istediğinizden emin misiniz ?\',\'warning\',\'DeleteCategory\',' + data.Id + ') " class="btn btn-danger"><i class="fa fa-trash-o"></i></button>';
                    }
                }
            ],
            'autoWidth': false
        });
    }
}

$(document).ready(function () {
    CategoryListTableReload();
    $("#SelectedParentProductCategoryId").select2();
});

var ParentCategoryName = "";

function recursiveIteration(object) {
   
    for (var property in object) {
        if (object.hasOwnProperty(property) && property == "ParentProductCategory") {
            if (typeof object[property] == "object") {
                var tmpObj = object[property];
              
                if (tmpObj != null) {

                    if (ParentCategoryName != '')
                        ParentCategoryName += " , " + tmpObj.Name;
                    else
                        ParentCategoryName = tmpObj.Name;

                    recursiveIteration(object[property]);
                }

            } else {
            }
        }
    }
}

function AddOrEditModal(Id) {
    debugger;
    $("#ProductCategoryModel_Id").val('');
    $("#modal-UpsertCategory").find('h4')[0].innerHTML = "Yeni Category Ekle";
    $("#ProductCategoryModel_Name").val('');
    $('#SelectedParentProductCategoryId').val('');
    $('#SelectedParentProductCategoryId').trigger('change');
    $('#fupPreview').attr("src", "");

    $('#SelectedParentProductCategoryId option').each(function () {
        debugger;
        $(this).prop('disabled', false);
    });

    if (Id != null) {

        //$.blockUI({ message: $('#domMessage') });
        $.ajax({
            url: "/Category/GetCategoryById?Id=" + Id,
            type: 'GET',

            datatype: 'json',
            success: function (data) {
                debugger;
                $("#ProductCategoryModel_Id").val(data.ProductCategoryModel.Id);
                $("#ProductCategoryModel_Name").val(data.ProductCategoryModel.Name);

                if (data.ProductCategoryModel.Status == 0)
                    $('#ProductCategoryModel_StatusFCheckBox').prop('checked', true);
                else
                    $('#ProductCategoryModel_StatusFCheckBox').prop('checked', false);


                if (data.ProductCategoryModel.Id > 0) {
                    $("#SelectedParentProductCategoryId option[value='" + data.ProductCategoryModel.Id + "']").prop('disabled', true);
                    //$('#SelectedParentProductCategoryId option:contains(' + data.ProductCategoryModel.Id + ')').attr("disabled", "disabled");
                }

                if (data.ProductCategoryModel.Media != null && data.ProductCategoryModel.Media.Link != null) {
                    $('#fupPreview').attr("src", window.location.protocol + '//' + window.location.host + '/' + data.ProductCategoryModel.Media.Link);
                }
                else {
                    $('#fupPreview').attr("src", window.location.protocol + '//' + window.location.host + '/Uploads/Media/noimage.png');
                }

                if (data.ProductCategoryModel.ParentId != null && data.ProductCategoryModel.ParentId > 0) {
                    $('#SelectedParentProductCategoryId').val(data.ProductCategoryModel.ParentId);
                    $('#SelectedParentProductCategoryId').trigger('change');
                }

                $("#modal-UpsertCategory").find('h4')[0].innerHTML = "(" + data.ProductCategoryModel.Id + ") nolu Category Güncelle";

                //$("#SelectedProductCategoryId").val(data.ProductModel.CategoryId).trigger("chosen:updated");
                //$("#Branch_Amount").val(data.Branch.Amount);
                //$("#Branch_ValidTo").val(data.Branch.ValidTo);
                //$("#Branch_ValidFrom").val(data.Branch.ValidFrom);
                //$("#frmDrBranchProviderSubType_Modal").find('h4')[0].innerHTML = data.Branch.ModalPopupDesc;
                //$.unblockUI();
            }

        });
    }

    $('#modal-UpsertCategory').modal("toggle");
}

(function () {

    $('#FormUpsertCategory').ajaxForm({
        beforeSend: function () {
            //$.blockUI({ message: $('#domMessage') });
        },
        success: function (data) {
            debugger;
            if (!data.IsSuccess) {
                Notify('Category Eklenemedi', data.ErrorMessage.toString(), 'warning');
            }
            else {

                Notify('Başarılı', "Category Eklendi", 'succuess');
                $('#modal-UpsertCategory').modal('hide');
            }

        }, complete: function (xhr) {
            CategoryListTableReload();
        }

    })

})();

function DeleteCategory(id) {
    if (id != null) {
        $.ajax({
            url: "/Category/DeleteCategory",
            type: 'POST',
            data: { 'Id': id },
            datatype: 'json',
            success: function (data) {
                if (data.IsSuccess == true) {
                    Notify('Başarılı', 'Category Silinmistir', 'success');
                    CategoryListTableReload();
                }
                else
                    Notify('Başarısız', data.ErrorMessage.toString(), 'warning');
            }
        });
    }
}
</script>